#INSTALL DEPENDANCI
FROM python:3.10-slim as builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --user -r requirements.txt

#BUILD THE FINAL IMAGE 

FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

COPY . .

CMD ["python", "app.py"]


